engines:
  rubocop:
    enabled: false
  bundler-audit:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "*.rb"
exclude_paths:
- app/assets/images/*
- config/**/*
- data/**/*
- db/**/*
- bin/**/*
- spec/**/*
- vendor/**/*
